/run/numberOfThreads 1

/g4cmp/phononBounces 1000
/g4cmp/filmThicknessAl 300
/g4cmp/filmThicknessNb 40
/g4cmp/primFileName Primary_Al300_Nb40.txt
/g4cmp/hitsFileName Hits_Al300_Nb40.txt

/run/initialize
/tracking/verbose 0
/run/printProgress 1000

# Generate 1 phonon per event. Place uniformly throughout the chip
/gps/number 1
/gps/particle phononL

#Now we generate from a volume instead of a point
/gps/pos/type Volume
/gps/pos/shape Para
/random/setSeeds 2
/gps/ang/type iso
/gps/pos/centre 0.0 0.0 0.0 cm # halfway between bottom and top of chip # Default
/gps/pos/halfx 0.5 cm  #Chip half-width
/gps/pos/halfy 0.5 cm  #Chip half-width
/gps/pos/halfz 0.04 mm #Chip half-thickness

#Select energies
/gps/ene/type Mono
/gps/energy 0.004 eV 
/run/beamOn 25000
