/run/numberOfThreads 14

/g4cmp/phononBounces 1000000
/g4cmp/filmThicknessAl 500
/g4cmp/filmThicknessNb 20
/g4cmp/Al true
/g4cmp/pAbsProbSideWallSi 0.0
/g4cmp/pAbsProbPolishedWallSi 0.0025
/g4cmp/numsensors 2
/g4cmp/primFileName ./260419_run/lQPD_Al_PF/Primary_Al500_ns2.txt
/g4cmp/hitsFileName ./260419_run/lQPD_Al_PF/Hits_Al500_ns2.txt

/run/initialize
/tracking/verbose 0
/run/printProgress 1000

# Generate 1 phonon per event. Place uniformly throughout the chip
/gps/number 1
/gps/particle phononL

#Now we generate from a volume instead of a point
/gps/pos/type Volume
/gps/pos/shape Para
/random/setSeeds 2
/gps/ang/type iso
/gps/pos/centre 0.0 0.0 0.0 cm # halfway between bottom and top of chip # Default
/gps/pos/halfx .35355 cm  #Chip half-width
/gps/pos/halfy .35355 cm  #Chip half-width
/gps/pos/halfz 0.04 mm #Chip half-thickness

#Select energies
/gps/ene/type Mono
/gps/energy 0.004 eV 
/run/beamOn 10000
