/run/numberOfThreads 14

/g4cmp/phononBounces 100000
/g4cmp/filmThicknessAl 600
/g4cmp/filmThicknessNb 20
/g4cmp/Al true
/g4cmp/pAbsProbSideWallSi 0.01
/g4cmp/pAbsProbPolishedWallSi 0.0
/g4cmp/primFileName ./260519_run/MEMS_Al_SW/Primary_Al600_Nb20_ix4_iy6.txt
/g4cmp/hitsFileName ./260519_run/MEMS_Al_SW/Hits_Al600_Nb20_ix4_iy6.txt

/run/initialize
/tracking/verbose 0
/run/printProgress 1000

# Generate 1 phonon per event from a point on an 8x8 grid across the 1cm x 1cm chip
/gps/number 1
/gps/particle phononL

/gps/pos/type Point
/random/setSeeds 2
/gps/ang/type iso
/gps/pos/centre 0 .2222 0.0 cm

#Select energies
/gps/ene/type Mono
/gps/energy 0.004 eV 
/run/beamOn 1000
