/run/numberOfThreads 14

/g4cmp/phononBounces 1000000
/g4cmp/filmThicknessAl 100
/g4cmp/filmThicknessNb 20
/g4cmp/Al false
/g4cmp/pAbsProbSideWallSi 0.01
/g4cmp/pAbsProbPolishedWallSi 0.0
/g4cmp/numsensors 1
/g4cmp/primFileName ./260908_run/MEMS_Al_Nb_SW/Primary_Al100_Nb20_ix17_iy17.txt
/g4cmp/hitsFileName ./260908_run/MEMS_Al_Nb_SW/Hits_Al100_Nb20_ix17_iy17.txt

/run/initialize
/tracking/verbose 0
/run/printProgress 1000

# Generate 1 phonon per event from a point on an 8x8 grid across the 1cm x 1cm chip
/gps/number 1
/gps/particle phononL

/gps/pos/type Point
/random/setSeeds 2
/gps/ang/type iso
/gps/pos/centre .3750 .3750 0.0 cm

#Select energies
/gps/ene/type Mono
/gps/energy 0.004 eV 
/run/beamOn 5000
