/run/initialize

/vis/open OGL
/vis/viewer/set/upVector 0 1 0
/vis/viewer/set/viewpointVector 0 0 1
# Zoom in to see the 5mm chip (World is 160mm)
/vis/viewer/zoom 30
/vis/drawVolume

# Write event display to output files for analysis (face and side views)
/vis/ogl/set/printFilename g4cmpPhonon
/vis/ogl/set/printMode vectored
/vis/ogl/printEPS

/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointVector 0 1 0
/vis/viewer/zoomTo 30
/vis/ogl/printEPS
